export const browserCoreExamples = [
  "crabfork browser status",
  "crabfork browser start",
  "crabfork browser stop",
  "crabfork browser tabs",
  "crabfork browser open https://example.com",
  "crabfork browser focus abcd1234",
  "crabfork browser close abcd1234",
  "crabfork browser screenshot",
  "crabfork browser screenshot --full-page",
  "crabfork browser screenshot --ref 12",
  "crabfork browser snapshot",
  "crabfork browser snapshot --format aria --limit 200",
  "crabfork browser snapshot --efficient",
  "crabfork browser snapshot --labels",
];

export const browserActionExamples = [
  "crabfork browser navigate https://example.com",
  "crabfork browser resize 1280 720",
  "crabfork browser click 12 --double",
  'crabfork browser type 23 "hello" --submit',
  "crabfork browser press Enter",
  "crabfork browser hover 44",
  "crabfork browser drag 10 11",
  "crabfork browser select 9 OptionA OptionB",
  "crabfork browser upload /tmp/crabfork/uploads/file.pdf",
  'crabfork browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "crabfork browser dialog --accept",
  'crabfork browser wait --text "Done"',
  "crabfork browser evaluate --fn '(el) => el.textContent' --ref 7",
  "crabfork browser console --level error",
  "crabfork browser pdf",
];
